### ISSUE TITLE
How do you use this plug-in?

### ISSUE THREAD

**Issue by lanceh1412** [madeingnecca/sublime-find-non-ascii#1]
Hi,
I've installed this plug-in - now what? Can't see how to use it. I want to find all non ascii chars in a text file. Have loaded it into sublime, installed this package but can't see how to get it to highlight non-ascii chars.

**Comment by madeingnecca** [comment]
open the command palette (ctrl + shift + p, on win) and select "find non ascii".
Hope this helps,
Damiano

**Comment by lanceh1412** [comment]
Thank you.
