### ISSUE TITLE
How does this package work?

### ISSUE THREAD

**Issue by alecive** [madeingnecca/sublime-find-non-ascii#2]
Hello @madeingnecca , I wondered how this package works. Are the non ASCII characters automatically highlighted? Do I need a special keybinding?

**Comment by madeingnecca** [comment]
see #1 :)

**Comment by alecive** [comment]
Thank you @madeingnecca .

Do you mind adding it to your `README.md`? It's not that useful to have the how-to nested into the repository's issues.
